;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="IFP.Containers.Identifier.Item",DevComment="")
+GameplayTagList=(Tag="IFP.Containers.Identifier.Player.Grid",DevComment="")
+GameplayTagList=(Tag="Item.Flora.Leaves",DevComment="")
+GameplayTagList=(Tag="Item.Mineral.Quartz",DevComment="")
+GameplayTagList=(Tag="Player.Inventory.Container",DevComment="")

+GameplayTags=(Tag="IFP.ItemData.Rarity", DevComment="Base rarity tag")
+GameplayTags=(Tag="IFP.ItemData.Rarity.1-Common", DevComment="Common rarity")
+GameplayTags=(Tag="IFP.ItemData.Rarity.2-Uncommon", DevComment="Uncommon rarity")
+GameplayTags=(Tag="IFP.ItemData.Rarity.3-Rare", DevComment="Rare rarity")
+GameplayTags=(Tag="IFP.ItemData.Rarity.4-Epic", DevComment="Epic rarity")
+GameplayTags=(Tag="IFP.ItemData.Rarity.5-Legendary", DevComment="Legendary rarity")
+GameplayTags=(Tag="IFP.Items.Status.IsEquipped", DevComment="Item is equipped")
+GameplayTags=(Tag="IFP.ItemData.Rules.CantBeRotated", DevComment="Item cannot be rotated")
+GameplayTags=(Tag="IFP.Tiles.Hidden", DevComment="Tile is hidden")
+GameplayTags=(Tag="IFP.Tiles.Locked", DevComment="Tile is locked")
+GameplayTags=(Tag="IFP.Drivers.FinishResponse.Equipped", DevComment="Finish response for equipped item")
+GameplayTags=(Tag="IFP.Drivers.FinishResponse.Unequipped", DevComment="Finish response for unequipped item")
+GameplayTags=(Tag="IFP.Items.Stat.DurabilityMax", DevComment="Max durability stat")
+GameplayTags=(Tag="IFP.Items.Stat.Durability", DevComment="Current durability stat")
+GameplayTags=(Tag="IFP.Items.Status.IsNew", DevComment="Item is new")
+GameplayTags=(Tag="IFP.Event.ItemUsed", DevComment="Item was used")
+GameplayTags=(Tag="IFP.Containers.Identifier.Player.Back", DevComment="Player container back identifier")
+GameplayTags=(Tag="IFP.Containers.Identifier.Player.Helmet", DevComment="Player container helmet identifier")
+GameplayTags=(Tag="IFP.Containers.Identifier.Player.Standard", DevComment="Player container standard identifier")
+GameplayTags=(Tag="IFP.Containers.Identifier.Player.Weapon", DevComment="Player container weapon identifier")
+GameplayTags=(Tag="IFP.Containers.Identifier.Player.DataOnly", DevComment="Player container data only identifier")
+GameplayTags=(Tag="IFP.Containers.Identifier.Player.RPG.QuickSlot1", DevComment="Player RPG quick slot identifier")

